#TekNoise Game Save
#Mon May 11 05:51:00 PST 2026
candlePuzzleSolved=false
characterChoice=2
currentMapPath=/maps/stage01.txt
developerMode=true
firstEnemyHintPending=false
firstEnemyHintTicksRemaining=0
gameState=1
litCandleOrder=
masterVolume=0.7
monsterDimmingDialoguePending=false
monsterDimmingDialogueShown=false
player.direction=down
player.hasAxe=false
player.hasKey=0
player.hasReplacementSwitch=false
player.life=5
player.maxLife=5
player.speed=2.5
player.stageX=144
player.stageY=528
saveTime=1778449860024
stage01DoorRevealPlayed=false
stage02BossActivated=false
stage02BossIntroPlayed=false
stage3BarrierBroken=false
stage3ChaseStarted=false
