#TekNoise Game Save
#Mon May 11 15:44:51 PST 2026
candlePuzzleSolved=false
characterChoice=3
currentMapPath=/maps/stage01.txt
developerMode=false
firstEnemyHintPending=false
firstEnemyHintTicksRemaining=0
gameState=11
litCandleOrder=
masterVolume=0.4
monsterDimmingDialoguePending=false
monsterDimmingDialogueShown=false
player.direction=up
player.hasAxe=false
player.hasKey=0
player.hasReplacementSwitch=false
player.life=5
player.maxLife=5
player.speed=2.5
player.stageX=137
player.stageY=319
saveTime=1778485491170
stage01DoorRevealPlayed=false
stage02BossActivated=false
stage02BossIntroPlayed=false
stage3BarrierBroken=false
stage3ChaseStarted=false
